# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_auto_20180313_1023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='MyEvent',
        ),
    ]
