# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0008_auto_20180313_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myevent',
            options={'get_latest_by': 'event_date'},
        ),
    ]
