# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0009_auto_20180313_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='unitlimit',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
